export const leadgenConfig = {
  icp: {
    label: "Тестовый ICP: B2B-технологические компании с заметным сигналом роста",
    note: "Временный зашитый ICP для первой итерации процесса Leadgen OS.",
    languages: ["en", "ru"],
    industries: {
      en: [
        "B2B SaaS",
        "enterprise software",
        "CRM software",
        "sales automation",
        "marketing automation",
        "workflow automation",
        "AI platform",
      ],
      ru: [
        "B2B SaaS",
        "корпоративное ПО",
        "CRM",
        "автоматизация продаж",
        "маркетинговая автоматизация",
        "автоматизация бизнес-процессов",
        "AI платформа",
      ],
    },
    companyTypes: {
      en: [
        "software company",
        "SaaS company",
        "technology company",
        "platform",
        "startup",
      ],
      ru: [
        "IT-компания",
        "SaaS-компания",
        "технологическая компания",
        "платформа",
        "стартап",
      ],
    },
    keywords: {
      en: [
        "sales",
        "growth",
        "revenue",
        "customer success",
        "automation",
        "AI",
        "CRM",
      ],
      ru: [
        "продажи",
        "рост",
        "выручка",
        "клиентский успех",
        "автоматизация",
        "ИИ",
        "CRM",
      ],
    },
    signalPriorities: {
      HIRING_SIGNAL: 90,
      GO_TO_MARKET_SIGNAL: 100,
      GROWTH_SIGNAL: 85,
      CONTENT_SIGNAL: 70,
      TRAFFIC_SIGNAL: 80,
      TECH_SIGNAL: 90,
    },
    signalSourceHints: {
      HIRING_SIGNAL: {
        en: [
          "company careers page",
          "job board",
          "LinkedIn Jobs",
          "Greenhouse",
          "Lever",
          "Indeed",
          "Glassdoor",
        ],
        ru: [
          "HH",
          "карьерная страница компании",
          "раздел вакансии",
          "работа в компании",
          "открытые вакансии",
        ],
      },
      GO_TO_MARKET_SIGNAL: {
        en: [
          "company website",
          "product page",
          "press release",
          "company blog",
          "news",
          "integration page",
          "pricing page",
        ],
        ru: [
          "сайт компании",
          "новости компании",
          "пресс-релиз",
          "страница продукта",
          "новый сервис",
          "новый тариф",
          "интеграция",
        ],
      },
      GROWTH_SIGNAL: {
        en: [
          "funding news",
          "company news",
          "press release",
          "expansion announcement",
          "new office",
          "team growth",
        ],
        ru: [
          "новости компании",
          "расширение",
          "инвестиции",
          "новый офис",
          "рост команды",
          "открытие филиала",
        ],
      },
      CONTENT_SIGNAL: {
        en: [
          "company blog",
          "YouTube",
          "LinkedIn company page",
          "resources",
          "case studies",
          "webinars",
          "podcast",
        ],
        ru: [
          "блог компании",
          "YouTube",
          "Telegram",
          "кейсы",
          "статьи",
          "вебинары",
          "подкасты",
          "медиа",
        ],
      },
      TRAFFIC_SIGNAL: {
        en: [
          "landing page",
          "book a demo page",
          "free trial page",
          "signup page",
          "webinar registration",
          "lead magnet",
        ],
        ru: [
          "лендинг",
          "оставить заявку",
          "демо",
          "бесплатный доступ",
          "регистрация",
          "лид-магнит",
          "пробный период",
        ],
      },
      TECH_SIGNAL: {
        en: [
          "integration page",
          "API docs",
          "product updates",
          "automation page",
          "AI feature page",
          "CRM integration",
        ],
        ru: [
          "интеграции",
          "API",
          "автоматизация",
          "ИИ",
          "CRM",
          "цифровизация",
          "обновления продукта",
        ],
      },
    },
  },
  offer: {
    label: "Разбор точек роста в исходящих коммуникациях",
    note: "Временная клиентская формулировка. Заменить после проверки ICP и оффера.",
  },
} as const;
